#!/usr/bin/env bash
# Generates Homepage's config files (services.yaml, widgets.yaml, settings.yaml,
# bookmarks.yaml, docker.yaml) from .env — run after Sonarr/Radarr/Prowlarr have
# started at least once (their API keys don't exist until then, same
# requirement as post-setup.sh). Safe to re-run any time to pick up new keys
# from .env — e.g. add JELLYFIN_API_KEY/SEERR_API_KEY/BAZARR_API_KEY/
# TAILSCALE_API_KEY+TAILSCALE_DEVICE_ID later to turn those links into widgets.
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$DIR/.env"
[[ -f $ENV_FILE ]] || { echo "No se encontró $ENV_FILE"; exit 1; }
set -a; source "$ENV_FILE"; set +a

STORAGE=${STORAGE:-/mnt/storage}
: "${SONARR_API_KEY:?Falta SONARR_API_KEY en .env — arranca sonarr y ejecuta post-setup.sh primero}"
: "${RADARR_API_KEY:?Falta RADARR_API_KEY en .env — arranca radarr y ejecuta post-setup.sh primero}"
: "${QBITTORRENT_PASSWORD:?Falta QBITTORRENT_PASSWORD en .env}"

CONFIG_DIR="$STORAGE/config/homepage"
mkdir -p "$CONFIG_DIR"

# Prowlarr shares the Servarr config.xml format, so its key can be read the
# same way post-setup.sh reads Sonarr/Radarr's — no need to store it in .env.
PROWLARR_CONFIG="$STORAGE/config/prowlarr/config.xml"
if [[ -f $PROWLARR_CONFIG ]]; then
    PROWLARR_API_KEY=$(grep -o "<ApiKey>[^<]*</ApiKey>" "$PROWLARR_CONFIG" | sed "s/<[^>]*>//g")
else
    echo "Prowlarr no ha arrancado todavía, omito su widget (solo tendrá el enlace)."
    PROWLARR_API_KEY=""
fi

# Jellyfin, Seerr, Bazarr and Tailscale don't auto-generate an API key/token
# like the Servarr apps do, so these stay link-only unless you create one
# yourself and add it to .env — see README "Homepage" section.
JELLYFIN_API_KEY="${JELLYFIN_API_KEY:-}"
SEERR_API_KEY="${SEERR_API_KEY:-}"
BAZARR_API_KEY="${BAZARR_API_KEY:-}"
TAILSCALE_API_KEY="${TAILSCALE_API_KEY:-}"
TAILSCALE_DEVICE_ID="${TAILSCALE_DEVICE_ID:-}"
[[ -z $JELLYFIN_API_KEY ]] && echo "JELLYFIN_API_KEY no está en .env, omito su widget (solo tendrá el enlace)."
[[ -z $SEERR_API_KEY ]] && echo "SEERR_API_KEY no está en .env, omito su widget (solo tendrá el enlace)."
[[ -z $BAZARR_API_KEY ]] && echo "BAZARR_API_KEY no está en .env, omito su widget (solo tendrá el enlace)."
[[ -z $TAILSCALE_API_KEY || -z $TAILSCALE_DEVICE_ID ]] && echo "TAILSCALE_API_KEY/TAILSCALE_DEVICE_ID no están en .env, omito su widget."

# Optional visual theme. Set HOMEPAGE_THEME=cyberpunk in .env for a neon/dark
# look (accent color + scanline overlay + glowing headings/links via
# custom.css). Anything else (or unset) keeps the plain default look.
HOMEPAGE_THEME="${HOMEPAGE_THEME:-default}"
if [[ "$HOMEPAGE_THEME" == "cyberpunk" ]]; then
    HOMEPAGE_COLOR="cyan"
else
    HOMEPAGE_COLOR="slate"
fi

cat > "$CONFIG_DIR/settings.yaml" <<EOF
title: jellyPi
theme: dark
color: ${HOMEPAGE_COLOR}
headerStyle: clean
layout:
  Media:
    style: row
    columns: 2
  Downloads & Automation:
    style: row
    columns: 3
  System:
    style: row
    columns: 3
EOF

cat > "$CONFIG_DIR/widgets.yaml" <<'EOF'
- resources:
    label: Pi
    cpu: true
    memory: true
    disk: /
- resources:
    label: HDD
    disk: /mnt/storage
- search:
    provider: duckduckgo
    target: _blank
EOF

cat > "$CONFIG_DIR/bookmarks.yaml" <<'EOF'
EOF

# Required for every "server: localhost" reference in services.yaml — Homepage
# has no implicit default docker instance, so without this file it errors with
# "Cannot read properties of null (reading 'localhost')".
cat > "$CONFIG_DIR/docker.yaml" <<'EOF'
localhost:
  socket: /var/run/docker.sock
EOF

# Homepage auto-loads config/custom.css if present. We use only
# global/generic selectors here (body, headings, links, scrollbar) rather
# than Homepage's internal Tailwind classes, which aren't a stable public API
# and could silently stop matching after a Homepage update. Re-running this
# script with HOMEPAGE_THEME unset/anything else writes an empty file,
# cleanly reverting to the default look.
if [[ "$HOMEPAGE_THEME" == "cyberpunk" ]]; then
    cat > "$CONFIG_DIR/custom.css" <<'EOF'
/* Cyberpunk theme — generated by homepage-setup.sh (HOMEPAGE_THEME=cyberpunk) */
body {
  background-color: #000;
  /* Dark vignette, a faint circuit-board grid, and a dot at each grid cell
     (chip/PCB blueprint look) — all pure CSS, no external image requests. */
  background-image:
    radial-gradient(circle at 50% 0%, #0d1117 0%, #000 60%),
    linear-gradient(rgba(0, 255, 255, 0.07) 1px, transparent 1px),
    linear-gradient(90deg, rgba(0, 255, 255, 0.07) 1px, transparent 1px),
    radial-gradient(circle, rgba(0, 255, 255, 0.25) 1.5px, transparent 1.5px);
  background-size: 100% 100%, 42px 42px, 42px 42px, 42px 42px;
  background-attachment: fixed;
}

/* Faint scanline overlay across the whole page */
body::before {
  content: "";
  position: fixed;
  inset: 0;
  pointer-events: none;
  z-index: 9999;
  background: repeating-linear-gradient(
    0deg,
    rgba(0, 255, 255, 0.035) 0px,
    rgba(0, 255, 255, 0.035) 1px,
    transparent 1px,
    transparent 3px
  );
  mix-blend-mode: overlay;
}

h1, h2, h3, h4 {
  text-shadow: 0 0 6px #0ff, 0 0 12px #0ff, 0 0 24px rgba(0, 255, 255, 0.6);
}

a {
  transition: text-shadow 0.2s ease, color 0.2s ease;
}
a:hover {
  color: #ff00ea !important;
  text-shadow: 0 0 6px #ff00ea, 0 0 14px #ff00ea;
}

::selection {
  background: #ff00ea;
  color: #000;
}

::-webkit-scrollbar {
  width: 10px;
}
::-webkit-scrollbar-track {
  background: #000;
}
::-webkit-scrollbar-thumb {
  background: linear-gradient(180deg, #0ff, #ff00ea);
  border-radius: 6px;
}
EOF
else
    : > "$CONFIG_DIR/custom.css"
fi

cat > "$CONFIG_DIR/services.yaml" <<EOF
- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://jellypi.local:8096
        description: Movies, TV and anime
        server: localhost
        container: jellyfin
$( [[ -n $JELLYFIN_API_KEY ]] && cat <<EOF2
        widgets:
          - type: jellyfin
            url: http://jellyfin:8096
            key: "${JELLYFIN_API_KEY}"
            version: 2
            enableBlocks: true
            enableNowPlaying: true
            fields: ["movies", "series", "episodes"]
EOF2
)
    - Seerr:
        icon: overseerr.png
        href: http://jellypi.local:5055
        description: Request movies and shows
        server: localhost
        container: seerr
$( [[ -n $SEERR_API_KEY ]] && cat <<EOF2
        widgets:
          - type: seerr
            url: http://seerr:5055
            key: "${SEERR_API_KEY}"
EOF2
)

- Downloads & Automation:
    - qBittorrent:
        icon: qbittorrent.png
        href: http://jellypi.local:8080
        description: Torrent client (via Gluetun VPN)
        server: localhost
        container: qbittorrent
        widgets:
          - type: qbittorrent
            url: http://gluetun:8080
            username: admin
            password: "${QBITTORRENT_PASSWORD}"
            enableLeechProgress: true

    - Sonarr:
        icon: sonarr.png
        href: http://jellypi.local:8989
        description: TV shows automation
        server: localhost
        container: sonarr
        widgets:
          - type: sonarr
            url: http://sonarr:8989
            key: "${SONARR_API_KEY}"

    - Radarr:
        icon: radarr.png
        href: http://jellypi.local:7878
        description: Movies automation
        server: localhost
        container: radarr
        widgets:
          - type: radarr
            url: http://radarr:7878
            key: "${RADARR_API_KEY}"

    - Prowlarr:
        icon: prowlarr.png
        href: http://jellypi.local:9696
        description: Indexer manager
        server: localhost
        container: prowlarr
$( [[ -n $PROWLARR_API_KEY ]] && cat <<EOF2
        widgets:
          - type: prowlarr
            url: http://prowlarr:9696
            key: "${PROWLARR_API_KEY}"
EOF2
)
    - Bazarr:
        icon: bazarr.png
        href: http://jellypi.local:6767
        description: Subtitles automation
        server: localhost
        container: bazarr
$( [[ -n $BAZARR_API_KEY ]] && cat <<EOF2
        widgets:
          - type: bazarr
            url: http://bazarr:6767
            key: "${BAZARR_API_KEY}"
EOF2
)

- System:
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: http://jellypi.local:3001
        description: Service monitoring
        server: localhost
        container: uptime-kuma

    - FlareSolverr:
        icon: flaresolverr.png
        description: Cloudflare bypass for indexers
        server: localhost
        container: flaresolverr

    - Gluetun:
        icon: gluetun.png
        description: VPN for qBittorrent
        server: localhost
        container: gluetun

    - Tailscale:
        icon: tailscale.png
        href: https://login.tailscale.com/admin/machines
        description: Remote access VPN
        server: localhost
        container: tailscale
$( [[ -n $TAILSCALE_API_KEY && -n $TAILSCALE_DEVICE_ID ]] && cat <<EOF2
        widgets:
          - type: tailscale
            deviceid: "${TAILSCALE_DEVICE_ID}"
            key: "${TAILSCALE_API_KEY}"
            fields: ["address", "update_available"]
EOF2
)
EOF

chmod 600 "$CONFIG_DIR/services.yaml"

echo "Config de Homepage generada en $CONFIG_DIR"
echo "Aplica los cambios con: docker compose restart homepage"
echo "(igual que decluttarr: 'up -d' no basta, no detecta cambios en archivos montados por bind mount)"
